### ISSUE TITLE
Better documentation on setting label names

### ISSUE THREAD

**Issue by timc3** [mtanda/grafana-google-stackdriver-datasource#14]
> Please specify path to label name from top of TimeSeries object. For example, if you want to get instance name, set metric.labels.instance_name to path to label name.

Maybe it's my poor knowledge of Grafana, but I think that this needs to be clearer. I have no idea what you mean.

**Comment by mtanda** [comment]
Sorry for my poor English and explanation. It is Stackdriver specific thing, not Grafana.
You can get arbitrary value from Stackdriver's TimeSeries object, and set to template variable.

Internally, this plugin use [Lodash property method](https://lodash.com/docs/4.17.5#property) to get label value from TimeSeries JSON object, please specify path for JSON object member.

Example query:
```
label_values(some_project, metric.labels.instance_name, metric.type = "compute.googleapis.com/instance/cpu/utilization")
```

**Comment by timc3** [comment]
Ok, 👍 Thanks for the explanation.
