### ISSUE TITLE
Resource types and custom tags?

### ISSUE THREAD

**Issue by algermissen** [mtanda/grafana-google-stackdriver-datasource#18]
Hi,

I have been playing around with your plugin a bit and here is some feedback / questions:

- There is definitely too little feedback/information if oauth2 dance goes wrong. Especially if you are not doing oauth stuff as daily business, the complexity when it comes to finding an error is huge. Good error messages and hints what to do would help a great deal.
- Do you plan to support resource types and the associated additional metrics at some point? Just having the metrics types list is definitely not enough for serious work with GCP setups.
- Do you plan to support filtering and aggregating based on resource tags/labels - it is also essential to do something useful - especially when automating dashboard creation

But thanks for the great work - stackdriver as such is not scriptable and cannot be parameterized, so sth like your plugin is essential for building on top of stackdriver.

Jan

**Comment by mtanda** [comment]
Thanks for feedback!

> There is definitely too little feedback/information if oauth2 dance goes wrong. Especially if you are not doing oauth stuff as daily business, the complexity when it comes to finding an error is huge. Good error messages and hints what to do would help a great deal.

Agree, sometimes I have trouble to setup datasource. Need to improve.

> Do you plan to support resource types and the associated additional metrics at some point? Just having the metrics types list is definitely not enough for serious work with GCP setups.

Sorry, I'm not sure what `resource types and the associated additional metrics` is.

To filter resource types, specify query like `resource.type = "gce_instance"`.
https://cloud.google.com/monitoring/api/v3/filters

> Do you plan to support filtering and aggregating based on resource tags/labels - it is also essential to do something useful - especially when automating dashboard creation

Sorry again, I'm not sure what `resource tags/labels` is.
If stackdriver support filtering and aggregation for these, this datasource plugin should support it.

I'm beginner about GCP, so I need more details to add features.

**Comment by algermissen** [comment]
Hi, this is strange. I guess I am stupid. Now I can see all the metrics. I spent hours and hours with stack driver last weeks and maybe I just understand it better.

Thank you, that was still helpful :-)

**Comment by mtanda** [comment]
Sorry for the inconvenience.
If your problems are solved, it's really nice :-)
I'm not sure why the problems occur, so if you replicate same problems again, please report me!
