### ISSUE TITLE
How to install in Docker/Kubernetes?

### ISSUE THREAD

**Issue by cypressious** [mtanda/grafana-google-stackdriver-datasource#19]
I'm interested in trying out this plugin. However, I don't see instructions on how to install it when Grafana is running in Kubernetes.

I'm currently using the Helm package from https://github.com/kubernetes/charts/tree/master/stable/grafana.

**Comment by ericuldall** [comment]
I'm not sure if it makes a difference when installing with helm, but I currently run Grafana in Kubernetes and I do the following.

1. Exec into the grafana pod
2. Git clone the repo into the plugins directory
3. Delete the pod and let kubernetes recreate it

I set up grafana with a persistent disk mounted as follows:
```
volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-storage
```

This makes it pretty easy to just exec onto the pod and use the grafana cli or manually install third party plugins. When the pod is deleted it will get restarted and all of the data in /var/lib/grafana will be persisted. If you don't have a similar setup you'll probably need to run some sort of lifcycle hook when your pod starts to install any necessary dependencies or roll your own docker image in a similar fashion.

**Comment by cypressious** [comment]
@ericuldall thanks for the comment. I ended up using `kubectl cp` to copy the directory to the pod. I'm using the same `volumeMounts` and it's working great.

**Comment by mtanda** [comment]
Thanks for answering.
Seems to be solved, close this.
