### ISSUE TITLE
`Access: Server` reports 'Data source is working' but metric queries do not return results

### ISSUE THREAD

**Issue by mweiden** [mtanda/grafana-google-stackdriver-datasource#27]
### What Grafana version are you using?
5.0.4

### What datasource are you using?
https://github.com/mtanda/grafana-google-stackdriver-datasource

### What OS are you running grafana on?
Linux (derived from grafana/grafana docker image)

### What did you do?
* Set the google application credentials in a docker container. See output below
```bash
root@778f9f78fcdc:/# echo $GOOGLE_APPLICATION_CREDENTIALS
/gcp-credentials.json
```
* Configure the datasource, `Save & Test` reports it to be working. See output below

![screen shot 2018-05-23 at 10 05 14 am](https://user-images.githubusercontent.com/538456/40440118-fa6a4ed8-5e71-11e8-8a2c-14fec8d3037b.png)

### What was the expected result?
Access to google stackdriver metrics

### What happened instead?
No response is returned from the metrics server. See console output below.

```javascript
TypeError: Cannot read property 'timeSeries' of undefined
    at eval (datasource.ts:404)
    at u (angular.js:17145)
    at angular.js:17193
    at d.$digest (angular.js:18331)
    at d.$apply (angular.js:18628)
    at angular.js:18931
    at i (angular.js:6419)
    at angular.js:6699
metrics_panel_ctrl.ts:159 Panel data error: SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at eval (datasource.ts:77)
```

![screen shot 2018-05-23 at 10 14 32 am](https://user-images.githubusercontent.com/538456/40440215-4fe0fac4-5e72-11e8-8bee-fcba22b84afe.png)

**Comment by mweiden** [comment]
@mtanda Re: https://github.com/mtanda/grafana-google-stackdriver-datasource/pull/24 I think you made some progress here, but I don't think this is working currently.

**Comment by mtanda** [comment]
@mweiden Sorry, I forget to tell you important point.
You need to use Grafana nightly build.
The backend code is depend on https://github.com/grafana/grafana/commit/4533f22871c207764f704f6280a555febe4c7c50#diff-36fa1b3501cb9f21b877adee5dc840c5 .
It is not released yet...

Sorry again, to waste your time

**Comment by mweiden** [comment]
@mtanda ah, your right, with the latest image this works. Thanks!

**Comment by mtanda** [comment]
@mweiden Thanks for testing!
