### ISSUE TITLE
Metrics pulled resolve to value of 0, not a numeric value

### ISSUE THREAD

**Issue by AndrewFarley** [mtanda/grafana-google-stackdriver-datasource#35]
When using a singlestat panel, when I try to use the value mapping feature or the threshold feature, no matter what the numeric value is shown, the value that it resolves to is "0".  I'm assuming there is a text-to-int problem somewhere here, since I confirmed it doesn't happen via other data sources (Prometheus / CloudWatch) I'm assuming this problem lies in this plugin.

After further testing, this seems to occur with ALL metrics pulled from this plugin, not limited to counts.  But, I initially found this problem when using the COUNT align feature.

The following four panel screenshot below have the exact same configuration...
 * They all pull a metric which equals 1
 * They all have the threshhold coloring feature enabled
 * The right two have the value mapping feature enabled, the left two show the raw value
 * The top two are from stackdriver, the bottom two from prometheus (and working properly, as a comparison)

<img width="510" alt="screen shot 2018-08-09 at 5 58 45 pm" src="https://user-images.githubusercontent.com/470163/43910893-533a3f54-9bfe-11e8-9578-3fa77258da8f.png">

With the following configuration...
<img width="285" alt="screen shot 2018-08-09 at 5 41 24 pm" src="https://user-images.githubusercontent.com/470163/43910401-06ffc8c6-9bfd-11e8-9c2c-b83893968aa0.png">
<img width="334" alt="screen shot 2018-08-09 at 6 01 25 pm" src="https://user-images.githubusercontent.com/470163/43910870-48d6b9d4-9bfe-11e8-9a76-47d8829cc9a3.png">
The configuration (which is not relevant, as this appears to apply to ALL metrics) looks like...
<img width="1103" alt="screen shot 2018-08-09 at 5 41 54 pm" src="https://user-images.githubusercontent.com/470163/43910385-fc4b9b62-9bfc-11e8-9e10-ea2a46df5130.png">

As I said this appears to be wide-reaching, every metric I pull from stackdriver appears to render to a value of "0" for the purposes of this the singlestat panel, effectively rendering the major visual feedback feature of the singlestat panel absolutely useless.

**Comment by AndrewFarley** [comment]
What I believe is related, is if you hover over any value in a graph, it also doesn't show you the value of that area.  So this damage isn't limited to only the singlestat panel.

**Comment by AndrewFarley** [comment]
After further research, it looks like the problem may lie in the fact that this plugin returns timeseries  data instead of returning a series, or a matrix.  Can this be adjusted...?

This plugin:
```
{
  "results": {
    "": {
      "refId": "",
      "meta": {
        "timeSeries": [
          {
            "metric": {
              "type": "container.googleapis.com/container/memory/bytes_used"
            },
            "metricKind": "GAUGE",
            "points": [
              {
                "interval": {
                  "endTime": "2018-08-14T09:47:19.352Z",
                  "startTime": "2018-08-14T09:47:19.352Z"
                },
                "value": {
                  "int64Value": "3"
                }
              },
```

CloudWatch...
```
{
  "results": {
    "A": {
      "refId": "A",
      "series": [
        {
          "name": "CloudWatch CPU Usage - SingleStat",
          "points": [
            [
              6.95833333341094,
              1534236120000
            ],
            [
              8.04166666658906,
              1534236180000
            ],
```

Prometheus...
```
{
  "status": "success",
  "data": {
    "resultType": "matrix",
    "result": [
      {
        "metric": {},
        "values": [
          [
            1534238420,
            "86.82540911209465"
          ],
```

**Comment by mtanda** [comment]
@AndrewFarley sorry for late response.
I guess https://github.com/mtanda/grafana-google-stackdriver-datasource/pull/37 will resolve your issue.
Please test it.

**Comment by AndrewFarley** [comment]
Thanks, I will test it shortly!

**Comment by AndrewFarley** [comment]
@mtanda Fixed in master, thanks!

**Comment by AndrewFarley** [comment]
@mtanda I'll gladly buy you some more Dr. Pepper or something for this fix, and any continued support of this plugin.  Email me back sometime, cheers, and thanks!

**Comment by mtanda** [comment]
Thanks for testing!
